# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/jactivelte/setup-makefiles.sh

# Camera
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/Camera/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
        vendor/samsung/jactivelte/proprietary/Camera/bin/mm-qcamera-app:system/bin/mm-qcamera-app \
        vendor/samsung/jactivelte/proprietary/Camera/bin/mm-qcamera-test:system/bin/mm-qcamera-test \
        vendor/samsung/jactivelte/proprietary/Camera/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
        vendor/samsung/jactivelte/proprietary/Camera/cameradata/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
        vendor/samsung/jactivelte/proprietary/Camera/cameradata/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv \
        vendor/samsung/jactivelte/proprietary/Camera/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmmpo.so:system/lib/libmmmpo.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmmpod.so:system/lib/libmmmpod.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libgemini.so:system/lib/libgemini.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmercury.so:system/lib/libmercury.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libTsAwb.so:system/lib/libTsAwb.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libTsAccm.so:system/lib/libTsAccm.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmcamera_plugin.so:system/lib/libmmcamera_plugin.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmcamera_interface.so:system/lib/libmmcamera_interface.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmjpeg_interface.so:system/lib/libmmjpeg_interface.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/liboemcamera.so:system/lib/liboemcamera.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3h5xa_zsl.so:system/lib/libchromatix_s5k3h5xa_zsl.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3h5xa_default_video.so:system/lib/libchromatix_s5k3h5xa_default_video.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3h5xa_animation.so:system/lib/libchromatix_s5k3h5xa_animation.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3h5xa_antishake.so:system/lib/libchromatix_s5k3h5xa_antishake.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3h5xa_lls.so:system/lib/libchromatix_s5k3h5xa_lls.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3h5xa_preview.so:system/lib/libchromatix_s5k3h5xa_preview.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3h5xa_zsl_drama.so:system/lib/libchromatix_s5k3h5xa_zsl_drama.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3h5xa_zsl_panorama.so:system/lib/libchromatix_s5k3h5xa_zsl_panorama.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k6b2yx_pip.so:system/lib/libchromatix_s5k6b2yx_pip.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k6b2yx_preview.so:system/lib/libchromatix_s5k6b2yx_preview.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k6b2yx_smartstay.so:system/lib/libchromatix_s5k6b2yx_smartstay.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k6b2yx_video.so:system/lib/libchromatix_s5k6b2yx_video.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k6b2yx_vt.so:system/lib/libchromatix_s5k6b2yx_vt.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k6b2yx_vt_hd.so:system/lib/libchromatix_s5k6b2yx_vt_hd.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_ov2720_hfr.so:system/lib/libchromatix_ov2720_hfr.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_ov2720_zsl.so:system/lib/libchromatix_ov2720_zsl.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_ov8825_default_video.so:system/lib/libchromatix_ov8825_default_video.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_ov8825_preview.so:system/lib/libchromatix_ov8825_preview.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_ov9726_default_video.so:system/lib/libchromatix_ov9726_default_video.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_ov9726_preview.so:system/lib/libchromatix_ov9726_preview.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
        vendor/samsung/jactivelte/proprietary/Camera/lib/libvdis.so:system/lib/libvdis.so


# Radio
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libril.so:system/lib/libril.so \
        vendor/samsung/jactivelte/proprietary/Radio/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
        vendor/samsung/jactivelte/proprietary/Radio/bin/efsks:system/bin/efsks \
        vendor/samsung/jactivelte/proprietary/Radio/bin/ks:system/bin/ks \
        vendor/samsung/jactivelte/proprietary/Radio/bin/netmgrd:system/bin/netmgrd \
        vendor/samsung/jactivelte/proprietary/Radio/bin/sec-ril:system/bin/sec-ril \
        vendor/samsung/jactivelte/proprietary/Radio/bin/qcks:system/bin/qcks \
        vendor/samsung/jactivelte/proprietary/Radio/bin/qmiproxy:system/bin/qmiproxy \
        vendor/samsung/jactivelte/proprietary/Radio/bin/qmuxd:system/bin/qmuxd \
        vendor/samsung/jactivelte/proprietary/Radio/bin/rild:system/bin/rild \
        vendor/samsung/jactivelte/proprietary/Radio/bin/rmt_storage:system/bin/rmt_storage \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libatparser.so:system/lib/libatparser.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libcordon.so:system/lib/libcordon.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libdiag.so:system/lib/libdiag.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libdsutils.so:system/lib/libdsutils.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libidl.so:system/lib/libidl.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libnetmgr.so:system/lib/libnetmgr.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libqdi.so:system/lib/libqdi.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libqdp.so:system/lib/libqdp.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libqmi.so:system/lib/libqmi.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libqmiservices.so:system/lib/libqmiservices.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libreference-ril.so:system/lib/libreference-ril.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
        vendor/samsung/jactivelte/proprietary/Radio/lib/libsecril-client.so:system/lib/libsecril-client.so

        
# Bins
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/Bins/bin/mpdecision:system/bin/mpdecision \
        vendor/samsung/jactivelte/proprietary/Bins/bin/radish:system/bin/radish


# Thermal
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/Thermal/bin/thermald:system/bin/thermald \
        vendor/samsung/jactivelte/proprietary/Thermal/bin/thermal-engine:system/bin/thermal-engine


# Bluetooth firmware
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/BT_fw/vendor/firmware/bcm2079xB4_firmware.ncd:system/vendor/firmware/bcm2079xB4_firmware.ncd \
        vendor/samsung/jactivelte/proprietary/BT_fw/vendor/firmware/bcm2079xB4_pre_firmware.ncd:system/vendor/firmware/bcm2079xB4_pre_firmware.ncd \
        vendor/samsung/jactivelte/proprietary/BT_fw/vendor/firmware/bcm4335.hcd:system/vendor/firmware/bcm4335.hcd \
        vendor/samsung/jactivelte/proprietary/BT_fw/vendor/firmware/bcm4335_A0.hcd:system/vendor/firmware/bcm4335_A0.hcd \
        vendor/samsung/jactivelte/proprietary/BT_fw/vendor/firmware/bcm4335_murata.hcd:system/vendor/firmware/bcm4335_murata.hcd \
        vendor/samsung/jactivelte/proprietary/BT_fw/vendor/firmware/bcm4335_semco.hcd:system/vendor/firmware/bcm4335_semco.hcd

# Audio
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/Audio/lib/libacdbloader.so:system/lib/libacdbloader.so \
        vendor/samsung/jactivelte/proprietary/Audio/lib/libaudcal.so:system/lib/libaudcal.so \
        vendor/samsung/jactivelte/proprietary/Audio/lib/libcsd-client.so:system/lib/libcsd-client.so


# mmparser extended
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/mmparser/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
        vendor/samsung/jactivelte/proprietary/mmparser/lib/libmmparser.so:system/lib/libmmparser.so \
        vendor/samsung/jactivelte/proprietary/mmparser/lib/libmmosal.so:system/lib/libmmosal.so \
        vendor/samsung/jactivelte/proprietary/mmparser/lib/libdivxdrm.so:system/lib/libdivxdrm.so


# Adreno
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/Adreno/lib/libadreno_utils.so:system/lib/libadreno_utils.so \
        vendor/samsung/jactivelte/proprietary/Adreno/lib/libCB.so:system/lib/libCB.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/egl/libGLESv2S3D_adreno.so:system/vendor/lib/egl/libGLESv2S3D_adreno.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libOpenCL.so:system/vendor/lib/libOpenCL.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libOpenVG.so:system/vendor/lib/libOpenVG.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libc2d30.so:system/vendor/lib/libc2d30.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libllvm-a3xx.so:system/vendor/lib/libllvm-a3xx.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libqc-opt.so:system/vendor/lib/libqc-opt.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
        vendor/samsung/jactivelte/proprietary/Adreno/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
        vendor/samsung/jactivelte/proprietary/Adreno/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
        vendor/samsung/jactivelte/proprietary/Adreno/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
        vendor/samsung/jactivelte/proprietary/Adreno/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw


# Graphics
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/Graphics/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so


# Time services
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/TimeServices/bin/time_daemon:system/bin/time_daemon \
        vendor/samsung/jactivelte/proprietary/TimeServices/lib/libtime_genoff.so:system/lib/libtime_genoff.so


# GPS
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/GPS/lib/libgeofence.so:system/lib/libgeofence.so \
        vendor/samsung/jactivelte/proprietary/GPS/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so


# Sensors
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/Sensors/lib/libsensirion_j1.so:system/lib/libsensirion_j1.so \
        vendor/samsung/jactivelte/proprietary/Sensors/lib/libsam.so:system/lib/libsam.so \
        vendor/samsung/jactivelte/proprietary/Sensors/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
        vendor/samsung/jactivelte/proprietary/Sensors/lib/hw/sensorhubs.msm8960.so:system/lib/hw/sensorhubs.msm8960.so


# Wifi
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/bcmdhd_apsta.bin_a0:system/etc/wifi/bcmdhd_apsta.bin_a0 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/bcmdhd_mfg.bin_a0:system/etc/wifi/bcmdhd_mfg.bin_a0 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/bcmdhd_sta.bin_a0:system/etc/wifi/bcmdhd_sta.bin_a0 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/cred.conf:system/etc/wifi/cred.conf \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_mfg.txt_a0:system/etc/wifi/nvram_mfg.txt_a0 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_mfg.txt_murata:system/etc/wifi/nvram_mfg.txt_murata \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_mfg.txt_murata_a0:system/etc/wifi/nvram_mfg.txt_murata_a0 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_mfg.txt_muratafem1:system/etc/wifi/nvram_mfg.txt_muratafem1 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_mfg.txt_muratafem2:system/etc/wifi/nvram_mfg.txt_muratafem2 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_mfg.txt_semco3rd:system/etc/wifi/nvram_mfg.txt_semco3rd \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_mfg.txt_semco3rd_a0:system/etc/wifi/nvram_mfg.txt_semco3rd_a0 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_mfg.txt_semcosh:system/etc/wifi/nvram_mfg.txt_semcosh \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_net.txt_a0:system/etc/wifi/nvram_net.txt_a0 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_net.txt_murata:system/etc/wifi/nvram_net.txt_murata \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_net.txt_murata_a0:system/etc/wifi/nvram_net.txt_murata_a0 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_net.txt_muratafem1:system/etc/wifi/nvram_net.txt_muratafem1 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_net.txt_muratafem2:system/etc/wifi/nvram_net.txt_muratafem2 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_net.txt_semco3rd:system/etc/wifi/nvram_net.txt_semco3rd \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_net.txt_semco3rd_a0:system/etc/wifi/nvram_net.txt_semco3rd_a0 \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/nvram_net.txt_semcosh:system/etc/wifi/nvram_net.txt_semcosh \
        vendor/samsung/jactivelte/proprietary/WiFi/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf


# Perf
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/Perf/lib/libqc-opt.so:system/lib/libqc-opt.so


# DRM
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/DRM/bin/qseecomd:system/bin/qseecomd \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libdrmfs.so:system/lib/libdrmfs.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libdrmtime.so:system/lib/libdrmtime.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libhdcp2.so:system/lib/libhdcp2.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libWVStreamControlAPI_L1.so:system/lib/libWVStreamControlAPI_L1.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libwvm.so:system/lib/libwvm.so
